<Project>
  <PropertyGroup>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <PropertyGroup Condition="'$(MSBuildProjectName)' == 'MistChess.Api'">
    <UserSecretsId>MistChess.Api</UserSecretsId>
  </PropertyGroup>
</Project>
