// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MistChess.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MistChess.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MistChessDbContext))]
    [Migration("20260726095620_AddMoveCommandReceipts")]
    partial class AddMoveCommandReceipts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MistChess.Infrastructure.Persistence.DrawOfferEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_id");

                    b.Property<Guid>("OfferedByPlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("offered_by_player_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("GameId")
                        .IsUnique()
                        .HasDatabaseName("ux_draw_offers_pending_game")
                        .HasFilter("\"status\" = 'Pending'");

                    b.HasIndex("OfferedByPlayerId");

                    b.ToTable("draw_offers", null, t =>
                        {
                            t.HasCheckConstraint("ck_draw_offers_status", "status IN ('Pending', 'Accepted', 'Rejected', 'Withdrawn')");
                        });
                });

            modelBuilder.Entity("MistChess.Infrastructure.Persistence.GameEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long?>("BlackMilliseconds")
                        .HasColumnType("bigint")
                        .HasColumnName("black_milliseconds");

                    b.Property<Guid>("BlackPlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("black_player_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<string>("InitialStateJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("initial_state");

                    b.Property<long?>("RedMilliseconds")
                        .HasColumnType("bigint")
                        .HasColumnName("red_milliseconds");

                    b.Property<Guid>("RedPlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("red_player_id");

                    b.Property<string>("ResultReason")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("result_reason");

                    b.Property<string>("RuleVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("rule_version");

                    b.Property<string>("SideToMove")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("side_to_move");

                    b.Property<string>("StateJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("state");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("TimeControl")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("time_control");

                    b.Property<DateTimeOffset?>("TurnStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("turn_started_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<string>("Winner")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("winner");

                    b.HasKey("Id");

                    b.HasIndex("BlackPlayerId")
                        .HasDatabaseName("ix_games_active_black_player")
                        .HasFilter("\"status\" <> 'Finished'");

                    b.HasIndex("RedPlayerId")
                        .HasDatabaseName("ix_games_active_red_player")
                        .HasFilter("\"status\" <> 'Finished'");

                    b.HasIndex("Status", "TurnStartedAt")
                        .HasDatabaseName("ix_games_active_clock");

                    b.ToTable("games", null, t =>
                        {
                            t.HasCheckConstraint("ck_games_clock", "(time_control IS NULL AND red_milliseconds IS NULL AND black_milliseconds IS NULL AND turn_started_at IS NULL) OR (time_control IS NOT NULL AND red_milliseconds >= 0 AND black_milliseconds >= 0)");

                            t.HasCheckConstraint("ck_games_distinct_players", "red_player_id <> black_player_id");

                            t.HasCheckConstraint("ck_games_result", "(status = 'Finished' AND result_reason IS NOT NULL AND finished_at IS NOT NULL) OR (status = 'Playing' AND result_reason IS NULL AND winner IS NULL AND finished_at IS NULL)");

                            t.HasCheckConstraint("ck_games_status", "status IN ('Playing', 'Finished')");
                        });
                });

            modelBuilder.Entity("MistChess.Infrastructure.Persistence.GamePlayerEntity", b =>
                {
                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_id");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("side");

                    b.HasKey("GameId", "PlayerId");

                    b.HasIndex("PlayerId")
                        .IsUnique()
                        .HasDatabaseName("ux_game_players_active_player")
                        .HasFilter("\"is_active\"");

                    b.HasIndex("GameId", "Side")
                        .IsUnique()
                        .HasDatabaseName("ux_game_players_side");

                    b.ToTable("game_players", null, t =>
                        {
                            t.HasCheckConstraint("ck_game_players_side", "side IN ('Red', 'Black')");
                        });
                });

            modelBuilder.Entity("MistChess.Infrastructure.Persistence.GuestSessionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("display_name");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_guest_sessions_expires_at");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_guest_sessions_token_hash");

                    b.ToTable("guest_sessions", null, t =>
                        {
                            t.HasCheckConstraint("ck_guest_sessions_expiry", "expires_at > created_at");
                        });
                });

            modelBuilder.Entity("MistChess.Infrastructure.Persistence.MatchmakingTicketEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ClientRequestId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("client_request_id");

                    b.Property<int>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid?>("GameId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_id");

                    b.Property<DateTimeOffset>("LastHeartbeatAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_heartbeat_at");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<string>("RuleVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("rule_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<string>("TimeControl")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("time_control");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_matchmaking_tickets_expiry")
                        .HasFilter("\"status\" = 'Searching'");

                    b.HasIndex("GameId");

                    b.HasIndex("PlayerId")
                        .IsUnique()
                        .HasDatabaseName("ux_matchmaking_tickets_active_player")
                        .HasFilter("\"status\" = 'Searching'");

                    b.HasIndex("PlayerId", "ClientRequestId")
                        .IsUnique()
                        .HasDatabaseName("ux_matchmaking_tickets_request");

                    b.HasIndex("Status", "RuleVersion", "TimeControl", "CreatedAt", "Id")
                        .HasDatabaseName("ix_matchmaking_tickets_pool_fifo");

                    b.ToTable("matchmaking_tickets", null, t =>
                        {
                            t.HasCheckConstraint("ck_matchmaking_tickets_expiry", "expires_at > created_at AND expires_at >= last_heartbeat_at");

                            t.HasCheckConstraint("ck_matchmaking_tickets_game", "(status = 'Matched' AND game_id IS NOT NULL) OR (status <> 'Matched' AND game_id IS NULL)");

                            t.HasCheckConstraint("ck_matchmaking_tickets_status", "status IN ('Searching', 'Matched', 'Cancelled', 'Expired')");
                        });
                });

            modelBuilder.Entity("MistChess.Infrastructure.Persistence.MoveCommandReceiptEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long?>("BlackMillisecondsAfter")
                        .HasColumnType("bigint")
                        .HasColumnName("black_milliseconds_after");

                    b.Property<string>("ClientMoveId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("client_move_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_id");

                    b.Property<long>("GameVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("game_version");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<long?>("RedMillisecondsAfter")
                        .HasColumnType("bigint")
                        .HasColumnName("red_milliseconds_after");

                    b.Property<string>("ResultReasonAfter")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("result_reason_after");

                    b.Property<string>("StateAfterJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("state_after");

                    b.Property<DateTimeOffset?>("TurnStartedAtAfter")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("turn_started_at_after");

                    b.Property<string>("WinnerAfter")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("winner_after");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("GameId", "PlayerId", "ClientMoveId")
                        .IsUnique()
                        .HasDatabaseName("ux_move_command_receipts_game_player_client_move");

                    b.ToTable("move_command_receipts", (string)null);
                });

            modelBuilder.Entity("MistChess.Infrastructure.Persistence.MoveEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long?>("BlackMillisecondsAfter")
                        .HasColumnType("bigint")
                        .HasColumnName("black_milliseconds_after");

                    b.Property<string>("CapturedPieceType")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("captured_piece_type");

                    b.Property<string>("ClientMoveId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("client_move_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("ElapsedMilliseconds")
                        .HasColumnType("bigint")
                        .HasColumnName("elapsed_milliseconds");

                    b.Property<byte>("FromFile")
                        .HasColumnType("smallint")
                        .HasColumnName("from_file");

                    b.Property<byte>("FromRank")
                        .HasColumnType("smallint")
                        .HasColumnName("from_rank");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_id");

                    b.Property<long>("GameVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("game_version");

                    b.Property<string>("MovingPieceType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("moving_piece_type");

                    b.Property<int>("Ply")
                        .HasColumnType("integer")
                        .HasColumnName("ply");

                    b.Property<string>("PositionKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("position_key");

                    b.Property<long?>("RedMillisecondsAfter")
                        .HasColumnType("bigint")
                        .HasColumnName("red_milliseconds_after");

                    b.Property<string>("ResultReasonAfter")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("result_reason_after");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("side");

                    b.Property<string>("StateAfterJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("state_after");

                    b.Property<byte>("ToFile")
                        .HasColumnType("smallint")
                        .HasColumnName("to_file");

                    b.Property<byte>("ToRank")
                        .HasColumnType("smallint")
                        .HasColumnName("to_rank");

                    b.Property<DateTimeOffset?>("TurnStartedAtAfter")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("turn_started_at_after");

                    b.Property<string>("WinnerAfter")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("winner_after");

                    b.HasKey("Id");

                    b.HasIndex("GameId", "ClientMoveId")
                        .IsUnique()
                        .HasDatabaseName("ux_moves_game_client_move");

                    b.HasIndex("GameId", "Ply")
                        .IsUnique()
                        .HasDatabaseName("ux_moves_game_ply");

                    b.ToTable("moves", null, t =>
                        {
                            t.HasCheckConstraint("ck_moves_from", "from_file BETWEEN 0 AND 8 AND from_rank BETWEEN 0 AND 9");

                            t.HasCheckConstraint("ck_moves_ply", "ply > 0");

                            t.HasCheckConstraint("ck_moves_to", "to_file BETWEEN 0 AND 8 AND to_rank BETWEEN 0 AND 9");
                        });
                });

            modelBuilder.Entity("MistChess.Infrastructure.Persistence.RoomEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatorPlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("creator_player_id");

                    b.Property<Guid?>("GameId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_id");

                    b.Property<string>("RuleVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("rule_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("TimeControl")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("time_control");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_rooms_code");

                    b.HasIndex("CreatorPlayerId");

                    b.HasIndex("GameId")
                        .IsUnique()
                        .HasDatabaseName("ux_rooms_game_id")
                        .HasFilter("\"game_id\" IS NOT NULL");

                    b.ToTable("rooms", null, t =>
                        {
                            t.HasCheckConstraint("ck_rooms_game", "(status IN ('Playing', 'Finished') AND game_id IS NOT NULL) OR (status IN ('WaitingForOpponent', 'WaitingForReady') AND game_id IS NULL)");

                            t.HasCheckConstraint("ck_rooms_status", "status IN ('WaitingForOpponent', 'WaitingForReady', 'Playing', 'Finished')");
                        });
                });

            modelBuilder.Entity("MistChess.Infrastructure.Persistence.RoomPlayerEntity", b =>
                {
                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<bool>("IsReady")
                        .HasColumnType("boolean")
                        .HasColumnName("is_ready");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<byte>("Seat")
                        .HasColumnType("smallint")
                        .HasColumnName("seat");

                    b.Property<string>("Side")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("side");

                    b.HasKey("RoomId", "PlayerId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("RoomId", "Seat")
                        .IsUnique()
                        .HasDatabaseName("ux_room_players_seat");

                    b.HasIndex("RoomId", "Side")
                        .IsUnique()
                        .HasDatabaseName("ux_room_players_side")
                        .HasFilter("\"side\" IS NOT NULL");

                    b.ToTable("room_players", null, t =>
                        {
                            t.HasCheckConstraint("ck_room_players_seat", "seat BETWEEN 0 AND 1");
                        });
                });

            modelBuilder.Entity("MistChess.Infrastructure.Persistence.DrawOfferEntity", b =>
                {
                    b.HasOne("MistChess.Infrastructure.Persistence.GameEntity", "Game")
                        .WithMany("DrawOffers")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MistChess.Infrastructure.Persistence.GuestSessionEntity", "OfferedByPlayer")
                        .WithMany()
                        .HasForeignKey("OfferedByPlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("OfferedByPlayer");
                });

            modelBuilder.Entity("MistChess.Infrastructure.Persistence.GameEntity", b =>
                {
                    b.HasOne("MistChess.Infrastructure.Persistence.GuestSessionEntity", "BlackPlayer")
                        .WithMany()
                        .HasForeignKey("BlackPlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MistChess.Infrastructure.Persistence.GuestSessionEntity", "RedPlayer")
                        .WithMany()
                        .HasForeignKey("RedPlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BlackPlayer");

                    b.Navigation("RedPlayer");
                });

            modelBuilder.Entity("MistChess.Infrastructure.Persistence.GamePlayerEntity", b =>
                {
                    b.HasOne("MistChess.Infrastructure.Persistence.GameEntity", "Game")
                        .WithMany("Players")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MistChess.Infrastructure.Persistence.GuestSessionEntity", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("MistChess.Infrastructure.Persistence.MatchmakingTicketEntity", b =>
                {
                    b.HasOne("MistChess.Infrastructure.Persistence.GameEntity", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MistChess.Infrastructure.Persistence.GuestSessionEntity", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("MistChess.Infrastructure.Persistence.MoveCommandReceiptEntity", b =>
                {
                    b.HasOne("MistChess.Infrastructure.Persistence.GameEntity", "Game")
                        .WithMany("MoveCommandReceipts")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MistChess.Infrastructure.Persistence.GuestSessionEntity", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("MistChess.Infrastructure.Persistence.MoveEntity", b =>
                {
                    b.HasOne("MistChess.Infrastructure.Persistence.GameEntity", "Game")
                        .WithMany("Moves")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("MistChess.Infrastructure.Persistence.RoomEntity", b =>
                {
                    b.HasOne("MistChess.Infrastructure.Persistence.GuestSessionEntity", "CreatorPlayer")
                        .WithMany()
                        .HasForeignKey("CreatorPlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MistChess.Infrastructure.Persistence.GameEntity", "Game")
                        .WithOne()
                        .HasForeignKey("MistChess.Infrastructure.Persistence.RoomEntity", "GameId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatorPlayer");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("MistChess.Infrastructure.Persistence.RoomPlayerEntity", b =>
                {
                    b.HasOne("MistChess.Infrastructure.Persistence.GuestSessionEntity", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MistChess.Infrastructure.Persistence.RoomEntity", "Room")
                        .WithMany("Players")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("MistChess.Infrastructure.Persistence.GameEntity", b =>
                {
                    b.Navigation("DrawOffers");

                    b.Navigation("MoveCommandReceipts");

                    b.Navigation("Moves");

                    b.Navigation("Players");
                });

            modelBuilder.Entity("MistChess.Infrastructure.Persistence.RoomEntity", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
